site_name: "EVA 2 / Spec"
site_url: ""
site_author: "Paweł Kucmus"
edit_uri: ""

copyright: Copyright &copy; 2020 Paweł Kucmus

repo_name: EVA-3D / eva-spec 
repo_url: https://github.com/EVA-3D/eva-spec
  
theme:
  logo: assets/logo_white_outline.svg
  favicon: assets/logo_white_outline.svg
  name: material
  language: en
  palette:
    scheme: slate
    primary: blue grey
    accent: teal
  # logo: images/logo.svg
  # favicon: images/favicon.png
  # features:
  #   - navigation.tabs

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages

extra_css:
  - css/extra.css

extra_javascript:
  - https://cdn.scaleflex.it/plugins/js-cloudimage-360-view/2.4.1/js-cloudimage-360-view.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/extra.js

markdown_extensions:
  - abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: EVA-3D
      repo: eva-spec 
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
